export { rule as noDeprecatedProps } from './no-deprecated-props'
export { rule as hasAccessibilityHint } from './has-accessibility-hint'
export { rule as hasValidAccessibilityActions } from './has-valid-accessibility-actions'
export { rule as noNestedTouchables } from './no-nested-touchables'
export { rule as noLongAlt } from '../basic/no-long-alt'
